name: On Commit

on:
  push:
    branches-ignore:
      - main

defaults:
  run:
    shell: bash -v {0}

env:
  GH_TOKEN: ${{ secrets.CROSS_REPO_GITHUB_TOKEN }}
  DEBUG: true

jobs:

  collect-info:
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ steps.repo.outputs.name }}
      repo-exists: ${{ steps.repo.outputs.exists }}

    steps:
      - name: Dump Context
        if: env.DEBUG
        run: echo "${{ toJson(github) }}"

      - name: Info about Target Repo
        id: repo
        run: |

          # GitHub translates all chars except [a-zA-Z0-9._-] into '-' for repos, so we'll do that too
          sanitized_branch=$(echo '${{ github.ref_name }}' | sed -e "s/[^a-zA-Z0-9._-]/-/g")
          target_repo_name="__branch_$sanitized_branch"
          echo "Target repo name -> $target_repo_name"
          echo "name=$target_repo_name" >> $GITHUB_OUTPUT

          # It's possible to be here and the repo doesn't exist yet
          gh repo view ${{ github.repository_owner }}/$target_repo_name > /dev/null
          if [ $? -eq 0 ]; then
            echo "Repo ${{ github.repository_owner }}/$target_repo_name exists"
            echo "exists=1" >> $GITHUB_OUTPUT;
          else
            echo "Repo ${{ github.repository_owner }}/$target_repo_name does not exist"
            echo "exists=0" >> $GITHUB_OUTPUT;
          fi

  publish-changes:
    runs-on: ubuntu-latest
    needs: collect-info
    if: needs.collect-info.outputs.repo-exists == 1

    steps:
      - name: Publish Changes to Branch Repo
        run: |
          git config --global user.username '${{ github.event.head_commit.author.username }}'
          git config --global user.name '${{ github.event.head_commit.author.name }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git config --global user.password '${{ secrets.CROSS_REPO_GITHUB_TOKEN }}'
          git clone https://github.com/${{ github.repository }} --branch "${{ github.ref_name }}" from
          git clone https://github.com/${{ github.repository_owner }}/${{ needs.collect-info.outputs.repo-name }} to
          rsync -r from/* to
          cd to
          git add .
          git config --get user.username
          git config --get user.name
          git config --get user.email
          git config --get user.password
          git commit -m '${{ github.event.head_commit.message }}'
          git push
